<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
class LinearRegressionGD(object):

    def __init__(self, eta=0.001, n_iter=20):
        self.eta = eta
        self.n_iter = n_iter

    def fit(self, X, y):
        self.w_ = np.zeros(1 + X.shape[1])
        self.cost_ = []

        for i in range(self.n_iter):
            output = self.net_input(X)
            errors = (y - output)
            self.w_[1:] += self.eta * X.T.dot(errors)
            self.w_[0] += self.eta * errors.sum()
            cost = (errors**2).sum() / 2.0
            self.cost_.append(cost)
        return self

    def net_input(self, X):
        return np.dot(X, self.w_[1:]) + self.w_[0]

In [7]:
import numpy as np

In [35]:
x_model = LinearRegressionGD(n_iter=100000, eta = 0.001)
res = x_model.fit(np.array([1,2,3]).reshape(-1,1),np.array([3,5,7]))
res.w_

array([1., 2.])

In [33]:
x_model = LinearRegressionGD(n_iter=500,eta = 0.1)
res = x_model.fit(np.array([1,2,3]).reshape(-1,1),np.array([3,5,7]))
res.w_

array([1., 2.])

In [46]:
x_model = LinearRegressionGD(n_iter=100,eta = 0.2)
res = x_model.fit(np.array([1,2,3]).reshape(-1,1),np.array([3,5,7]))
res.w_

array([-4.46681514e+36, -1.01541207e+37])